<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDF93xzZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDF93xzZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDF93xzZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDF93xzZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDF93xzZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'DF93xzZ',
<<<<<<< HEAD
    'container.build_id' => '895a6204',
    'container.build_time' => 1597916010,
=======
    'container.build_id' => '6c1457f8',
    'container.build_time' => 1597914750,
>>>>>>> 9164aa9ab8e45a9d3f1a33efc4fe5e45bb216097
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDF93xzZ');
